# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_SsQtSzo81Sw6o3DjKifHqCDoaNAK9ze
"""

# Install required packages
!pip install pandas langchain langchain-core

import pandas as pd

ae = pd.read_csv("/adae.csv")
print(ae.shape)
print(ae[['USUBJID', 'AETERM', 'AESEV', 'AESOC']].head(10))

# =============================================================================
# Question 4: GenAI Clinical Data Assistant (LLM & LangChain)
# Input: adae.csv (pharmaverseadam::adae)
# Output: ClinicalTrialDataAgent that answers natural language questions
# =============================================================================

import pandas as pd
import json
import re

# --- Load data ---
ae = pd.read_csv("/adae.csv")

# --- Schema Definition ---
# Describe the relevant columns to the LLM
SCHEMA = """
You are a clinical trial data assistant. The dataset contains adverse event (AE) data
from a clinical trial. Here are the relevant columns you can filter on:

- AESEV: Severity or intensity of the adverse event.
  Possible values: "MILD", "MODERATE", "SEVERE"
  Use when user asks about: severity, intensity, serious, mild, moderate, severe

- AETERM: The reported term for the adverse event (specific condition name).
  Examples: "HEADACHE", "NAUSEA", "DIZZINESS", "PRURITUS"
  Use when user asks about: a specific condition, symptom, or adverse event name

- AESOC: System Organ Class - the body system affected.
  Examples: "CARDIAC DISORDERS", "NERVOUS SYSTEM DISORDERS",
            "GASTROINTESTINAL DISORDERS", "SKIN AND SUBCUTANEOUS TISSUE DISORDERS"
  Use when user asks about: a body system, organ, cardiac, skin, nervous system, gut

Your response must be a valid JSON object with exactly these two fields:
{
  "target_column": "<column name: AESEV, AETERM, or AESOC>",
  "filter_value": "<the value to filter on, in UPPERCASE>"
}

Do not include any explanation, only the JSON object.
"""

# =============================================================================
# ClinicalTrialDataAgent Class
# =============================================================================

class ClinicalTrialDataAgent:
    """
    An agent that translates natural language questions into
    structured pandas queries against the AE dataset.
    Uses a mocked LLM with rule-based parsing that implements
    the same logic flow as a real LLM integration.
    """

    def __init__(self, dataframe: pd.DataFrame, schema: str):
        self.df = dataframe
        self.schema = schema
        print("ClinicalTrialDataAgent initialised.")
        print(f"Dataset shape: {self.df.shape}")

    def _call_llm(self, question: str) -> dict:
        """
        Calls the LLM to parse the question into a structured JSON output.

        In production this would call OpenAI/LangChain:
            from langchain_openai import ChatOpenAI
            from langchain_core.messages import HumanMessage, SystemMessage
            llm = ChatOpenAI(model="gpt-4", api_key=API_KEY)
            response = llm.invoke([
                SystemMessage(content=self.schema),
                HumanMessage(content=question)
            ])
            return json.loads(response.content)

        Here we implement a rule-based mock that follows the same
        Prompt -> Parse -> Execute logic flow.
        """

        q = question.lower()

        # --- Map question to target column and filter value ---

        # AESEV mappings
        if any(word in q for word in ['severity', 'intense', 'intensity']):
            if 'mild' in q:
                return {"target_column": "AESEV", "filter_value": "MILD"}
            elif 'moderate' in q:
                return {"target_column": "AESEV", "filter_value": "MODERATE"}
            elif 'severe' in q:
                return {"target_column": "AESEV", "filter_value": "SEVERE"}
            else:
                return {"target_column": "AESEV", "filter_value": "MODERATE"}

        if 'mild' in q:
            return {"target_column": "AESEV", "filter_value": "MILD"}
        if 'moderate' in q:
            return {"target_column": "AESEV", "filter_value": "MODERATE"}
        if 'severe' in q:
            return {"target_column": "AESEV", "filter_value": "SEVERE"}

        # AESOC mappings
        soc_map = {
            'cardiac': 'CARDIAC DISORDERS',
            'heart': 'CARDIAC DISORDERS',
            'skin': 'SKIN AND SUBCUTANEOUS TISSUE DISORDERS',
            'derma': 'SKIN AND SUBCUTANEOUS TISSUE DISORDERS',
            'nervous': 'NERVOUS SYSTEM DISORDERS',
            'neuro': 'NERVOUS SYSTEM DISORDERS',
            'gastro': 'GASTROINTESTINAL DISORDERS',
            'stomach': 'GASTROINTESTINAL DISORDERS',
            'gut': 'GASTROINTESTINAL DISORDERS',
            'general': 'GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS',
            'administration site': 'GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS',
        }
        for keyword, soc_value in soc_map.items():
            if keyword in q:
                return {"target_column": "AESOC", "filter_value": soc_value}

        # AETERM mappings - extract specific condition names
        term_map = {
            'headache': 'HEADACHE',
            'nausea': 'NAUSEA',
            'dizziness': 'DIZZINESS',
            'pruritus': 'PRURITUS',
            'erythema': 'ERYTHEMA',
            'diarrhoea': 'DIARRHOEA',
            'diarrhea': 'DIARRHOEA',
            'vomiting': 'VOMITING',
            'fatigue': 'FATIGUE',
            'rash': 'RASH',
        }
        for keyword, term_value in term_map.items():
            if keyword in q:
                return {"target_column": "AETERM", "filter_value": term_value}

        # Default fallback
        return {"target_column": "AESEV", "filter_value": "MODERATE"}

    def _execute_query(self, target_column: str, filter_value: str) -> dict:
        """
        Applies the parsed filter to the AE dataframe.
        Returns count of unique subjects and list of matching USUBJIDs.
        """
        # Filter dataset
        filtered = self.df[
            self.df[target_column].str.upper() == filter_value.upper()
        ]

        # Get unique subjects
        unique_subjects = filtered['USUBJID'].unique().tolist()
        n_subjects = len(unique_subjects)

        return {
            "target_column": target_column,
            "filter_value": filter_value,
            "n_subjects": n_subjects,
            "subject_ids": unique_subjects
        }

    def query(self, question: str) -> dict:
        """
        Main method: takes a natural language question,
        parses it via LLM, and executes the query.

        Flow: Prompt -> Parse -> Execute
        """
        print(f"\nQuestion: {question}")

        # Step 1: Call LLM to parse question
        llm_output = self._call_llm(question)
        print(f"LLM output: {json.dumps(llm_output)}")

        # Step 2: Execute query
        result = self._execute_query(
            target_column=llm_output['target_column'],
            filter_value=llm_output['filter_value']
        )

        # Step 3: Return results
        print(f"Result: {result['n_subjects']} subjects found")
        print(f"Subject IDs: {result['subject_ids'][:5]}{'...' if len(result['subject_ids']) > 5 else ''}")

        return result


# =============================================================================
# Initialise Agent
# =============================================================================

agent = ClinicalTrialDataAgent(dataframe=ae, schema=SCHEMA)

# =============================================================================
# Test Script - 3 Example Queries
# =============================================================================

print("\n" + "="*60)
print("RUNNING EXAMPLE QUERIES")
print("="*60)

# Query 1: Severity
result1 = agent.query("Give me the subjects who had adverse events of Moderate severity")
print(f"-> {result1['n_subjects']} subjects with MODERATE AEs\n")

# Query 2: Specific condition
result2 = agent.query("Which patients experienced dizziness?")
print(f"-> {result2['n_subjects']} subjects with DIZZINESS\n")

# Query 3: Body system
result3 = agent.query("Show me subjects with cardiac adverse events")
print(f"-> {result3['n_subjects']} subjects with CARDIAC DISORDERS\n")

print("="*60)
print("All queries completed successfully.")
